#include <sequanto/QtAutoGeneratedNameProperty.h>
#include <sequanto/QtUnnamedObjectStore.h>
#include <sequanto/QtWidgetNode.h>
#include <sequanto/ui.h>

using namespace sequanto::automation;

QtAutoGeneratedNameProperty::QtAutoGeneratedNameProperty ()
   : ReadOnlyBooleanPropertyNode(SQ_UI_NODE_AUTO_GENERATED_NAME)
{
}
   
bool QtAutoGeneratedNameProperty::GetValue ()
{
   QtWidgetNode * widgetNode = dynamic_cast<QtWidgetNode*>(this->GetParent());
   if ( widgetNode != NULL )
   {
      QWidget * widget = widgetNode->widget();
      if ( widget != NULL )
      {
         return QtUnnamedObjectStore::IsKnown(widget);
      }
   }
   return false;
}

